In [4]:
import pandas as pd

In [1]:
!kaggle datasets download -d yaswanthkumary/ai-recruitment-pipeline-dataset

Dataset URL: https://www.kaggle.com/datasets/yaswanthkumary/ai-recruitment-pipeline-dataset
License(s): MIT
Downloading ai-recruitment-pipeline-dataset.zip to d:\Resume-Screening-Matching-System\data_upload_S3

  0%|          | 0.00/18.9M [00:00<?, ?B/s]
  5%|▌         | 1.00M/18.9M [00:01<00:29, 632kB/s]
 11%|█         | 2.00M/18.9M [00:01<00:13, 1.27MB/s]
 16%|█▌        | 3.00M/18.9M [00:02<00:08, 2.06MB/s]
 27%|██▋       | 5.00M/18.9M [00:02<00:03, 3.88MB/s]
 37%|███▋      | 7.00M/18.9M [00:02<00:02, 5.95MB/s]
 48%|████▊     | 9.00M/18.9M [00:02<00:01, 7.86MB/s]
 58%|█████▊    | 11.0M/18.9M [00:02<00:00, 9.92MB/s]
 69%|██████▉   | 13.0M/18.9M [00:02<00:00, 11.2MB/s]
 85%|████████▍ | 16.0M/18.9M [00:02<00:00, 12.8MB/s]
100%|██████████| 18.9M/18.9M [00:03<00:00, 14.3MB/s]
100%|██████████| 18.9M/18.9M [00:03<00:00, 6.43MB/s]

In [2]:
import zipfile

with zipfile.ZipFile(
    'ai-recruitment-pipeline-dataset.zip',
    'r'
) as zip_ref:
    zip_ref.extractall('data')

In [5]:
df = pd.read_csv('data/dataset.csv')

In [6]:
df.head()

,ID,Name,Role,Transcript,Resume,decision,Reason_for_decision,Job_Description
0,jasojo159,Jason Jones,E-commerce Specialist,"Interviewer: Good morning, Jason. It's great t...",Here's a professional resume for Jason Jones:\...,reject,Lacked leadership skills for a senior position.,Be part of a passionate team at the forefront ...
1,annma759,Ann Marshall,Game Developer,Interview Scene\n\nA conference room with a ta...,Here's a professional resume for Ann Marshall:...,select,Strong technical skills in AI and ML.,Help us build the next-generation products as ...
2,patrmc729,Patrick Mcclain,Human Resources Specialist,Interview Setting: A conference room in a medi...,Here's a professional resume for Patrick Mccla...,reject,Insufficient system design expertise for senio...,We need a Human Resources Specialist to enhanc...
3,patrgr422,Patricia Gray,E-commerce Specialist,Here's a simulated professional interview for ...,Here's a professional resume for Patricia Gray...,select,Impressive leadership and communication abilit...,Be part of a passionate team at the forefront ...
4,amangr696,Amanda Gross,E-commerce Specialist,Here's the simulated interview:\n\nInterviewer...,Here's a professional resume for Amanda Gross:...,reject,Lacked leadership skills for a senior position.,We are looking for an experienced E-commerce S...

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10174 entries, 0 to 10173
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   10174 non-null  str
 1   Name                 10174 non-null  str
 2   Role                 10174 non-null  str
 3   Transcript           10174 non-null  str
 4   Resume               10174 non-null  str
 5   decision             10174 non-null  str
 6   Reason_for_decision  10174 non-null  str
 7   Job_Description      10174 non-null  str
dtypes: str(8)
memory usage: 636.0 KB

In [12]:
df.describe()

,ID,Name,Role,Transcript,Resume,decision,Reason_for_decision,Job_Description
count,10174,10174,10174,10174,10174,10174,10174,10174
unique,10171,8677,31,10174,10174,2,539,3446
top,michmo483,Ananya,Software Engineer,"Interviewer: Good morning, Jason. It's great t...",Here's a professional resume for Jason Jones:\...,reject,Insufficient system design expertise for senio...,Join our team as a Product Manager and leverag...
freq,2,21,853,1,1,5114,730,103

In [13]:
df.notnull().sum()

ID                     10174
Name                   10174
Role                   10174
Transcript             10174
Resume                 10174
decision               10174
Reason_for_decision    10174
Job_Description        10174
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [7]:
pd.set_option('display.max_rows', None)

df['Role'].value_counts()

Role
Data Scientist                  538
Software Engineer               480
Product Manager                 458
Data Engineer                   447
UI Engineer                     375
Data Analyst                    329
software engineer               307
data engineer                   307
product manager                 303
data scientist                  287
E-commerce Specialist           268
DevOps Engineer                 266
Machine Learning Engineer       265
Human Resources Specialist      262
Digital Marketing Specialist    260
Robotics Engineer               257
Cloud Architect                 254
QA Engineer                     251
Blockchain Developer            251
Mobile App Developer            247
Full Stack Developer            246
Database Administrator          243
Cloud Engineer                  240
Game Developer                  239
Content Writer                  238
AR/VR Developer                 237
Cybersecurity Analyst           234
UX Designer                     227
Business Analyst                226
AI Researcher                   225
Data Architect                  225
IT Support Specialist           224
System Administrator            223
data analyst                    183
ui designer                     155
ui engineer                     132
UI Designer                      71
Software Developer               66
Project Manager                  56
Network Engineer                 16
Graphic Designer                 15
AI Engineer                      13
HR Specialist                    12
Cybersecurity Specialist          9
UI/UX Designer                    7
Name: count, dtype: int64

In [9]:
role_mapping = {
    'data scientist': 'Data Scientist',
    'software engineer': 'Software Engineer',
    'product manager': 'Product Manager',
    'data engineer': 'Data Engineer',
    'data analyst': 'Data Analyst',
    'ui engineer': 'UI Engineer',
    'ui designer': 'UI Designer',
    'AI Engineer': 'AI Researcher',
    'HR Specialist': 'Human Resources Specialist',
    'Cybersecurity Specialist': 'Cybersecurity Analyst',
    'UI/UX Designer': 'UI Designer',
    'Graphic Designer': 'UI Designer',
    'Network Engineer': 'System Administrator',
    'Software Developer': 'Software Engineer'
}

df['Role'] = df['Role'].replace(role_mapping)

In [10]:
df['Role'].value_counts()

Role
Software Engineer               853
Data Scientist                  825
Product Manager                 761
Data Engineer                   754
Data Analyst                    512
UI Engineer                     507
Human Resources Specialist      274
E-commerce Specialist           268
DevOps Engineer                 266
Machine Learning Engineer       265
Digital Marketing Specialist    260
Robotics Engineer               257
Cloud Architect                 254
QA Engineer                     251
Blockchain Developer            251
UI Designer                     248
Mobile App Developer            247
Full Stack Developer            246
Database Administrator          243
Cybersecurity Analyst           243
Cloud Engineer                  240
Game Developer                  239
System Administrator            239
AI Researcher                   238
Content Writer                  238
AR/VR Developer                 237
UX Designer                     227
Business Analyst                226
Data Architect                  225
IT Support Specialist           224
Project Manager                  56
Name: count, dtype: int64

In [15]:
df[['Role', 'Resume']].to_csv('data/cleaned_dataset.csv', index=False)

In [16]:
data = pd.read_csv('data/cleaned_dataset.csv')

In [17]:
data.head()

,Role,Resume
0,E-commerce Specialist,Here's a professional resume for Jason Jones:\...
1,Game Developer,Here's a professional resume for Ann Marshall:...
2,Human Resources Specialist,Here's a professional resume for Patrick Mccla...
3,E-commerce Specialist,Here's a professional resume for Patricia Gray...
4,E-commerce Specialist,Here's a professional resume for Amanda Gross:...

In [18]:
data.nunique()

Role         31
Resume    10174
dtype: int64